version: '3.4'

services:

  spring-docker:
    container_name: spring-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 500MB
        reservations:
          memory: 125MB

